-- Portable attendance + face re-identification schema
-- Target tables: person, attendance, attendance_log
-- Notes:
-- 1) For PostgreSQL, replace AUTO_INCREMENT with GENERATED BY DEFAULT AS IDENTITY.
-- 2) For PostgreSQL, replace BLOB with BYTEA.
-- 3) For PostgreSQL, replace DATETIME with TIMESTAMP.

CREATE TABLE person (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    full_name VARCHAR(150) NULL,
    job_title VARCHAR(120) NULL,
    address VARCHAR(255) NULL,
    identity_photo_path VARCHAR(255) NULL,
    manual_presence_today BOOLEAN NULL,
    qr_code_data VARCHAR(255) NULL,
    face_embedding BLOB NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE attendance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    person_id INT NOT NULL,
    attendance_date DATE NOT NULL,
    first_seen_at DATETIME NOT NULL,
    last_seen_at DATETIME NOT NULL,
    source VARCHAR(10) DEFAULT 'AUTO',
    compliance_rate FLOAT NULL,
    helmet_detected BOOLEAN NULL,
    vest_detected BOOLEAN NULL,
    glasses_detected BOOLEAN NULL,
    boots_detected BOOLEAN NULL,
    equipment_status VARCHAR(30) NULL,
    CONSTRAINT fk_attendance_person
        FOREIGN KEY (person_id) REFERENCES person(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_person_day UNIQUE (person_id, attendance_date)
);

CREATE TABLE attendance_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    person_id INT NULL,
    detected_at DATETIME NULL,
    confidence FLOAT NULL,
    camera_id VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attendance_log_person
        FOREIGN KEY (person_id) REFERENCES person(id)
        ON DELETE SET NULL
);

CREATE INDEX idx_attendance_date ON attendance (attendance_date);
CREATE INDEX idx_attendance_log_time ON attendance_log (detected_at);
